---
- name: construir app_imagen de docker
  docker_image:
    build:
      path: /opt/{{ app_name }}
      dockerfile: /opt/{{ app_name }}/Dockerfiles/{{ app_image }}/Dockerfile
    name: "{{ app_image }}"
    tag: "{{ app_version }}"
    source: build

- name: construir lb_imagen de docker
  docker_image:
    build:
      path: /opt/{{ app_name }}
      dockerfile: /opt/{{ app_name }}/Dockerfiles/{{ lb_image }}/Dockerfile
    name: "{{ lb_image }}"
    tag: "{{ lb_version }}"
    source: build

- name: correr contenedores
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}:{{ item.version}}"
    detach: true
    networks:
      - name: custom-network
  loop: "{{ web_containers }}"

- name: correr lb container
  docker_container:
    name: "{{ lb_container_name }}"
    image: "{{ lb_container_image }}:{{ lb_container_version }}"
    detach: true
    networks:
      - name: custom-network
    ports:
      - 5555:5555
      - 8081:8081
      - 80:80
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
  
